"""update procurement schema

Revision ID: 5282de3c04bc
Revises: 20260506_0002
Create Date: 2026-05-14 23:49:24.881531
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5282de3c04bc'
down_revision: str | None = '20260506_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procurement_requests', 'target_country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('procurement_requests', 'quality_grade',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('procurement_requests', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('pending', 'in_progress', 'complete', 'failed', name='procurement_request_status'),
               existing_nullable=False)
    op.drop_constraint(op.f('reports_request_id_key'), 'reports', type_='unique')
    op.alter_column('suppliers', 'city',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('suppliers', 'region',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('suppliers', 'country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.drop_constraint(op.f('suppliers_email_key'), 'suppliers', type_='unique')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_unique_constraint(op.f('suppliers_email_key'), 'suppliers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('suppliers', 'country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('suppliers', 'region',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('suppliers', 'city',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(op.f('reports_request_id_key'), 'reports', ['request_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('procurement_requests', 'status',
               existing_type=sa.Enum('pending', 'in_progress', 'complete', 'failed', name='procurement_request_status'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('procurement_requests', 'quality_grade',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('procurement_requests', 'target_country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###
